-note-most-markdown = 마크다운 문법을 대부분 사용할 수 있습니다. (서체, 목록, 링크 등)
-note-no-markdown = 마크다운을 사용할 수 없습니다.
-note-editable = 게시하기 전에 정보를 변경할 수 있습니다.
-optional = 선택 사항
f-title = RustFest Global 2021 CFP
f-manage-download-t = 제안서 내려받기
f-manage-upload-btn = 제안서 올리기
f-submission-deadline-t = 제출 마감일
f-manage-auth-btn = 코드 보내기
f-submission-t = 제출
f-submission-lang-t = 제출할 언어를 선택하세요
f-proposal-description-t = 상세한 발표 내용
f-proposal-title-t = 발표 제목
f-submission-presentation-format-t = 발표 형식
f-submission-presentation-format-longform-t = { f-presentation-format-longform } (최대 50분)
-note-some-markdown = 서체 형식의 마크다운을 일부 사용할 수 있습니다.
f-submitter-name-t = 이름
f-manage-download-btn = 제안서 내려받기
f-submission-presentation-lang-t = 발표 언어
f-proposal-t = 제안서
f-proposal-summary-t = 간략한 발표 내용
f-contact-email-t = 이메일 주소
f-submission-presentation-format-standard-t = { f-presentation-format-standard } (최대 25분)
f-proposal-audience-beginner-friendly-t = ?
event-none = ?
f-form-notes = ?
f-submission-deadline = ?
f-presentation-format-standard = ?
f-presentation-format-longform = ?
f-presentation-format-other = ?
f-submission-presentation-format-other-t = ?
f-proposal-audience-t = ?
f-proposal-audience-some-rust-t = ?
f-proposal-audience-advanced-rust-t = ?
f-proposal-audience-all-audiences-t = ?
f-proposal-notes-t = ?
f-manage-t = ?
f-manage = ?
f-manage-auth = ?
f-manage-download = ?
f-submit-btn = ?
f-submit-confirm-btn = ?
f-proposal-highlight = ?
event-none-summary = ?
f-contact-t = ?
f-contact-email = ?
f-submit-dialog-t = ?
f-submit-status-sending-verification = ?
f-submit-status-enter-verification-code = ?
f-submit-status-success-t = ?
f-submit-status-success = ?
f-cancel-btn = ?
f-submission-lang = ?
f-submission-presentation-lang = ?
f-submission-presentation-format = ?
f-proposal-summary = ?
f-proposal-description = ?
f-proposal-audience = ?
f-proposal-notes = ?
f-submitter-t = ?
f-submitter-tagline-t = ?
f-submitter-tagline = ?
f-submitter-bio-t = ?
f-submitter-bio = ?
f-proposal-highlight-t = ?
f-submit-error-generic = ?
